// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByuNBbCIrtmkE3Tl0RRUBG7JvL8dskQX4',
    appId: '1:829958955031:web:5b12dee67dce14f35f3c52',
    messagingSenderId: '829958955031',
    projectId: 'my-notes-18366',
    authDomain: 'my-notes-18366.firebaseapp.com',
    storageBucket: 'my-notes-18366.firebasestorage.app',
    measurementId: 'G-3GMXK6BE1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMoFrbo5Xi31toR4-0l7kv3mCGtYwo2VY',
    appId: '1:829958955031:android:8e07402e8512d9a25f3c52',
    messagingSenderId: '829958955031',
    projectId: 'my-notes-18366',
    storageBucket: 'my-notes-18366.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG9r1aE9cLTd8rJ0y1Glrv2f4rEyw6EwY',
    appId: '1:829958955031:ios:4cbae9047b41344f5f3c52',
    messagingSenderId: '829958955031',
    projectId: 'my-notes-18366',
    storageBucket: 'my-notes-18366.firebasestorage.app',
    iosBundleId: 'com.reflections.ismail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG9r1aE9cLTd8rJ0y1Glrv2f4rEyw6EwY',
    appId: '1:829958955031:ios:47a6a62160a101a45f3c52',
    messagingSenderId: '829958955031',
    projectId: 'my-notes-18366',
    storageBucket: 'my-notes-18366.firebasestorage.app',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByuNBbCIrtmkE3Tl0RRUBG7JvL8dskQX4',
    appId: '1:829958955031:web:e9e80d58657821e85f3c52',
    messagingSenderId: '829958955031',
    projectId: 'my-notes-18366',
    authDomain: 'my-notes-18366.firebaseapp.com',
    storageBucket: 'my-notes-18366.firebasestorage.app',
    measurementId: 'G-JQV4CBGQDS',
  );

}